server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      #单机版
      defaultZone: http://localhost:6001/eureka/
      #集群版
      #defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/

#这个例子来说使用feign客户端负载自带的熔断机制  客户端熔断
# 为了演示在Feign中需要开启 Hystrix 演示可以故意关闭provider服务看返回
feign:
  hystrix:
    enabled: true # 开启服务熔断器