server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.common.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  application:
    name: gou-provider #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #单机版 Eureka 服务注册中心
      defaultZone: http://localhost:6001/eureka
      #集群版配置  集群版就是注册到多个Eureka服务
      #defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    # 指定实例ID,不然ID就会显示主机名了
    instanceId: ${spring.application.name}:${server.port} # 等价于gou-provider:8001
    prefer-ip-address: true #访问路径就会显示成IP地址 (eureka访问页面http://127.0.0.1:6001/ 鼠标放在实力id上,对应左下角信息条显示ip地址而非主机地址)


##dashboard监控相关 在被监控服务上添加暴露端点 加这个会影响bus总线的暴露点,会被覆盖掉
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream